# Generated by Django 3.1.3 on 2021-04-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='first_meet',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='univ',
        ),
    ]
